services:
  - type: web
    name: crm-agricola
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      echo "📦 Haciendo migraciones..." &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      echo "✅ Migraciones aplicadas" &&
      gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: crm-agricola.onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
