services:
  - type: web
    name: crm-agricola
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash setup.sh
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: crm-agricola.onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
