# Generated by Django 5.2.4 on 2025-07-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_interaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Administrador'), ('supervisor', 'Supervisor'), ('vendedor', 'Vendedor')], max_length=20),
        ),
    ]
