# Generated by Django 5.2.4 on 2025-07-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='main_crop',
            field=models.CharField(choices=[('mango', 'Mango'), ('aceituna', 'Aceituna'), ('vid', 'Vid'), ('aguacate', 'Aguacate'), ('other', 'Other')], max_length=50),
        ),
    ]
