# Generated by Django 5.2.4 on 2025-07-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_client_main_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('agricultor', 'Agricultor'), ('cooperativa', 'Cooperativa'), ('distribuidor', 'Distribuidor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('call', 'Llamada'), ('visit', 'Visita'), ('email', 'Email'), ('fair', 'Feria Agricola'), ('other', 'otro')], max_length=20),
        ),
    ]
