# Generated by Django 5.2.4 on 2025-07-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_client_client_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='main_crop',
            field=models.CharField(choices=[('mango', 'Mango'), ('aceituna', 'Aceituna'), ('vid', 'Vid'), ('aguacate', 'Aguacate'), ('other', 'Otro')], max_length=50),
        ),
    ]
