# Generated by Django 5.2.4 on 2025-07-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_client_main_crop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterestedProduct',
        ),
    ]
