# Generated by Django 5.2.4 on 2025-07-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_delete_interestedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='assigned_salesperson',
        ),
    ]
