# Generated by Django 5.2.4 on 2025-07-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_company_assigned_salesperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='main_crop',
            field=models.CharField(choices=[('mango', 'Mango'), ('aceituna', 'Aceituna'), ('vid', 'Vid'), ('aguacate', 'Aguacate'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('llamada', 'Llamada'), ('visita', 'Visita'), ('email', 'Email'), ('feria', 'Feria Agricola'), ('otro', 'otro')], max_length=20),
        ),
    ]
