# Generated by Django 5.2.4 on 2025-07-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_client_main_crop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('llamada', 'Llamada'), ('visita', 'Visita'), ('email', 'Email'), ('feria', 'Feria Agricola'), ('otro', 'Otro')], max_length=20),
        ),
    ]
